[S3]
S3_url='https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv'

[local_paths]
destination_folder='/tmp'
file_name='inventory.csv'
local_file_path='/tmp/inventory.csv'

[Snowflake]
    account = 'XGYVRXQ-WTB51361'
    warehouse = 'COMPUTE_WH'
    database = 'tpcds'
    schema = 'raw'
    table = 'inventory'
    role='accountadmin'
    stage_name = 'inv_Stage'