select
    _AIRBYTE_EXTRACTED_AT as extracted_at,
    CS_EXT_TAX as ext_tax,
    CS_ITEM_SK as item_sk,
    CS_NET_PAID as net_paid,
    CS_PROMO_SK as promo_sk,
    CS_QUANTITY as quantity,
    CS_COUPON_AMT as coupon_amt,
    CS_LIST_PRICE as list_price,
    CS_NET_PROFIT as net_profit,
    CS_SALES_PRICE as sales_price,
    CS_BILL_ADDR_SK as bill_addr_sk,
    CS_ORDER_NUMBER as order_number,
    CS_SHIP_ADDR_SK as ship_addr_sk,
    CS_SHIP_DATE_SK as ship_date_sk,
    CS_SHIP_MODE_SK as ship_mode_sk,
    CS_SOLD_DATE_SK as sold_date_sk,
    CS_SOLD_TIME_SK as sold_time_sk,
    CS_WAREHOUSE_SK as warehouse_sk,
    CS_BILL_CDEMO_SK as bill_cdemo_sk,
    CS_BILL_HDEMO_SK as bill_hdemo_sk,
    CS_EXT_SHIP_COST as ext_ship_cost,
    CS_SHIP_CDEMO_SK as ship_cdemo_sk,
    CS_SHIP_HDEMO_SK as ship_hdemo_sk,
    CS_CALL_CENTER_SK as call_center_sk,
    CS_EXT_LIST_PRICE as ext_list_price,
    CS_WHOLESALE_COST as wholesale_cost,
    CS_CATALOG_PAGE_SK as catalog_page_sk,
    CS_EXT_SALES_PRICE as ext_sales_price,
    CS_BILL_CUSTOMER_SK as bill_customer_sk,
    CS_EXT_DISCOUNT_AMT as ext_discount_amt,
    CS_NET_PAID_INC_TAX as net_paid_inc_tax,
    CS_SHIP_CUSTOMER_SK as ship_customer_sk,
    CS_NET_PAID_INC_SHIP as net_paid_inc_ship,
    CS_EXT_WHOLESALE_COST as ext_wholesale_cost,
    CS_NET_PAID_INC_SHIP_TAX as net_paid_inc_ship_tax
from
    {{source('tpcds','catalog_sales')}}
